module.exports = [
    {
        id: 22,
        date: "2023-04-10 19:00:01",
        happy: 8,
        sad: 2,
        frustrated: 8,
        stress: 10,
        sleep: 7,
        nutrition: 8,
        fitness: 6,
        social: 4,
        qualitytime: 4,
        highlight: "Yoga",
        lowlight: "Not enough time for myself",
        user_id: 1
    },
    {
        id: 21,
        date: "2023-04-09 19:00:01",
        happy: 7,
        sad: 2,
        frustrated: 6,
        stress: 8,
        sleep: 9,
        nutrition: 7,
        fitness: 9,
        social: 5,
        qualitytime: 6,
        highlight: "Yoga",
        lowlight: "Not enough time for myself",
        user_id: 1
    },
    {
        id: 20,
        date: "2023-04-08 19:00:01",
        happy: 9,
        sad: 3,
        frustrated: 4,
        stress: 6,
        sleep: 8,
        nutrition: 6,
        fitness: 6,
        social: 8,
        qualitytime: 6,
        highlight: "Family time",
        lowlight: "time pressure",
        user_id: 1
    },
    {
        id: 19,
        date: "2023-04-07 19:00:01",
        happy: 9,
        sad: 3,
        frustrated: 4,
        stress: 6,
        sleep: 8,
        nutrition: 6,
        fitness: 6,
        social: 8,
        qualitytime: 6,
        highlight: "Family time",
        lowlight: "time pressure",
        user_id: 1
    },
    {
        id: 18,
        date: "2023-04-06 19:00:01",
        happy: 8,
        sad: 4,
        frustrated: 7,
        stress: 9,
        sleep: 8,
        nutrition: 7,
        fitness: 7,
        social: 4,
        qualitytime: 4,
        highlight: "workout",
        lowlight: "time pressure",
        user_id: 1
    },
    {
        id: 17,
        date: "2023-04-05 19:00:01",
        happy: 7,
        sad: 4,
        frustrated: 7,
        stress: 8,
        sleep: 8,
        nutrition: 8,
        fitness: 9,
        social: 5,
        qualitytime: 5,
        highlight: "workout",
        lowlight: "time pressure",
        user_id: 1
    },
    {
        id: 16,
        date: "2023-04-04 19:00:01",
        happy: 7,
        sad: 4,
        frustrated: 7,
        stress: 7,
        sleep: 5,
        nutrition: 7,
        fitness: 6,
        social: 9,
        qualitytime: 8,
        highlight: "meeting up with friends",
        lowlight: "work",
        user_id: 1
    },
    {
        id: 15,
        date: "2023-04-03 19:00:01",
        happy: 5,
        sad: 6,
        frustrated: 8,
        stress: 6,
        sleep: 4,
        nutrition: 7,
        fitness: 9,
        social: 4,
        qualitytime: 4,
        highlight: "progress",
        lowlight: "mean people",
        user_id: 1
    },
    {
        id: 14,
        date: "2023-04-02 19:00:01",
        happy: 8,
        sad: 3,
        frustrated: 5,
        stress: 9,
        sleep: 6,
        nutrition: 8,
        fitness: 9,
        social: 7,
        qualitytime: 3,
        highlight: "me-time",
        lowlight: "time pressure",
        user_id: 1
    },
    {
        id: 13,
        date: "2023-04-01 19:00:01",
        happy: 6,
        sad: 6,
        frustrated: 8,
        stress: 9,
        sleep: 8,
        nutrition: 7,
        fitness: 6,
        social: 3,
        qualitytime: 3,
        highlight: "outdoor run",
        lowlight: "time pressure",
        user_id: 1
    }
];